# Generated by Django 6.0.7 on 2026-09-25 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_loan_delete_financialgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='date',
            field=models.DateField(default=datetime.date(2026, 9, 25)),
            preserve_default=False,
        ),
    ]
